from lingua import Language

SupportedLanguages = [
    Language.BOKMAL,
    Language.CATALAN,
    Language.CHINESE,
    Language.CZECH,
    Language.DANISH,
    Language.DUTCH,
    Language.ENGLISH,
    Language.FINNISH,
    Language.FRENCH,
    Language.GERMAN,
    Language.GREEK,
    Language.HUNGARIAN,
    Language.ICELANDIC,
    Language.ITALIAN,
    Language.LITHUANIAN,
    Language.LATVIAN,
    Language.NYNORSK,
    Language.POLISH,
    Language.PORTUGUESE,
    Language.ROMANIAN,
    Language.RUSSIAN,
    Language.SLOVAK,
    Language.SLOVENE,
    Language.SPANISH,
    Language.SWEDISH,
    Language.TURKISH,
]